version: '3.8'

services:
  # MongoDB service with simplified configuration
  mongodb:
    image: mongo:6
    container_name: drawit-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=LND2210@
    restart: always

# Volumes
volumes:
  mongodb_data:
    driver: local
