name: Android CI & Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and upload assets
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK as Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DrawIt-release-apk-${{ github.sha }}
        path: app/build/outputs/apk/release/app-release*.apk

    - name: Create GitHub Release (only for new tags)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
