name: Android CI & Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and upload assets
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Decode Keystore
      id: decode_keystore
      run: |
        KEYSTORE_PATH="$GITHUB_WORKSPACE/keystore.jks"
        echo "keystore_path=$KEYSTORE_PATH" >> $GITHUB_OUTPUT
        
        if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$KEYSTORE_PATH"
          echo "Keystore decoded successfully"
          echo "has_keystore=true" >> $GITHUB_OUTPUT
        else
          echo "No keystore provided, will build unsigned APK"
          touch "$KEYSTORE_PATH"
          echo "has_keystore=false" >> $GITHUB_OUTPUT
        fi

    - name: Build and Sign Release APK
      run: |
        # Create local.properties with Android SDK path
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        
        if [ "${{ steps.decode_keystore.outputs.has_keystore }}" == "true" ] && \
           [ -n "${{ secrets.KEYSTORE_PASSWORD }}" ] && \
           [ -n "${{ secrets.KEY_ALIAS }}" ] && \
           [ -n "${{ secrets.KEY_PASSWORD }}" ]; then
          
          # Add signing configuration to local.properties
          echo "signing.keystore=${{ steps.decode_keystore.outputs.keystore_path }}" >> local.properties
          echo "signing.password=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "signing.key=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "signing.keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties
          
          # Build signed APK
          ./gradlew assembleRelease
          echo "Built signed APK successfully"
        else
          echo "Missing signing configuration, building unsigned APK"
          ./gradlew assembleRelease
        fi

    - name: Upload APK as Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DrawIt-release-apk-${{ github.sha }}
        path: app/build/outputs/apk/release/app-release*.apk

    - name: Create GitHub Release (only for new tags)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
